version: "3.0"

services:
  api:
    container_name: "api"
    volumes:
      - ./app :/app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=$DATABASE_URL
      - SECRET_KEY=$SECRET_KEY